### ISSUE TITLE
Freezing UI thread in BrainCloudWrapper.Update

### ISSUE THREAD

**Issue by german-krasnikov** [getbraincloud/braincloud-csharp#93]
Hi. 
I have a freezing UI animation in my game when I use BrainCloudWrapper. You could see these moments on the screenshot. Could you try to do it in a different thread? As a solution, maybe will be better to use coroutines for that(https://docs.unity3d.com/Manual/BestPracticeUnderstandingPerformanceInUnity3.html). Or you could try to use UniRx(https://github.com/neuecc/UniRx#using-for-multithreading) the calculation do in a different thread and use method ObserveOnMainThread. 
With regards,
German
<img width="1668" alt="Screen Shot 2019-07-16 at 10 02 22 AM" src="https://user-images.githubusercontent.com/4676584/61265789-bd64df80-a7b3-11e9-8e87-9592df367762.png">

**Comment by german-krasnikov** [comment]
<img width="1680" alt="Screen Shot 2019-07-16 at 9 40 02 PM" src="https://user-images.githubusercontent.com/4676584/61308679-94c00280-a812-11e9-91fb-1eac9c2dc9e7.png">
![Uploading Screen Shot 2019-07-16 at 9.41.22 PM.png…]()

**Comment by german-krasnikov** [comment]
<img width="1678" alt="Screen Shot 2019-07-16 at 9 41 22 PM" src="https://user-images.githubusercontent.com/4676584/61308941-1f086680-a813-11e9-9c6b-7024435d0cf2.png">

**Comment by german-krasnikov** [comment]
<img width="1680" alt="Screen Shot 2019-07-17 at 7 21 49 AM" src="https://user-images.githubusercontent.com/4676584/61342006-830a4980-a86a-11e9-9da6-ad8766eefafc.png">
<img width="1676" alt="Screen Shot 2019-07-17 at 8 10 55 AM" src="https://user-images.githubusercontent.com/4676584/61342021-8b628480-a86a-11e9-872a-f64c88ce908a.png">
<img width="1792" alt="Screen Shot 2019-07-17 at 8 11 27 AM" src="https://user-images.githubusercontent.com/4676584/61342033-91586580-a86a-11e9-8db3-21235a5f4b27.png">

**Comment by ruth0048** [comment]
We added an additional define "BC_DEBUG_LOG_ENABLED"  to stop the logging unless otherwise desired for debugging.

If you are looking to re-enable the logs you will need to follow these steps:
1. Open up your project's solution in visual studio
2. Right click your .csproj and go to properties.
3. In properties, go to the BUILD tab, and under 'General' you will see "Conditional Compilation Symbols:"
4. In that box add BC_DEBUG_LOG_ENABLED;
5. This will then bypass our conditionals that are currently hiding those logs
